In [2]:
import numpy as np

You enter a large cavern full of rare bioluminescent dumbo octopuses! They seem to not like the Christmas lights on your submarine, so you turn them off for now.

There are 100 octopuses arranged neatly in a 10 by 10 grid. Each octopus slowly gains energy over time and flashes brightly for a moment when its energy is full. Although your lights are off, maybe you could navigate through the cave without disturbing the octopuses if you could predict when the flashes of light will happen.

Each octopus has an energy level - your submarine can remotely measure the energy level of each octopus (your puzzle input). For example:
```
5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526
```
The energy level of each octopus is a value between 0 and 9. Here, the top-left octopus has an energy level of 5, the bottom-right one has an energy level of 6, and so on.

You can model the energy levels and flashes of light in steps. During a single step, the following occurs:

First, the energy level of each octopus increases by 1.
Then, any octopus with an energy level greater than 9 flashes. This increases the energy level of all adjacent octopuses by 1, including octopuses that are diagonally adjacent. If this causes an octopus to have an energy level greater than 9, it also flashes. This process continues as long as new octopuses keep having their energy level increased beyond 9. (An octopus can only flash at most once per step.)
Finally, any octopus that flashed during this step has its energy level set to 0, as it used all of its energy to flash.
Adjacent flashes can cause an octopus to flash on a step even if it begins that step with very little energy. Consider the middle octopus with 1 energy in this situation:
```
Before any steps:
11111
19991
19191
19991
11111

After step 1:
34543
40004
50005
40004
34543

After step 2:
45654
51115
61116
51115
45654
```
An octopus is highlighted when it flashed during the given step.

After 100 steps, there have been a total of 1656 flashes.

Given the starting energy levels of the dumbo octopuses in your cavern, simulate 100 steps. How many total flashes are there after 100 steps?





In [7]:
aoc_day = '2021-12-11'
test_input_file = f"../test_inputs/{aoc_day}-input.txt"
input_file = f"../inputs/{aoc_day}-input.txt"
try_test_input = False


def preprocess_input(input:str) -> list:
    input = np.array([[int(x) for x in row] for row in input.split("\n") if row != ""])
    return input 

with open(test_input_file, 'r') as f:
    test_input = preprocess_input(f.read())

with open(input_file, 'r') as f:
    input = preprocess_input(f.read())

if try_test_input:
    input = test_input.copy()

input

array([[3, 3, 2, 2, 8, 7, 4, 6, 5, 2],
       [5, 6, 3, 6, 5, 8, 8, 8, 5, 7],
       [7, 7, 5, 5, 1, 1, 7, 5, 4, 8],
       [5, 8, 5, 4, 1, 2, 1, 8, 3, 3],
       [2, 8, 5, 6, 6, 8, 2, 4, 7, 7],
       [3, 1, 2, 4, 8, 7, 3, 8, 1, 2],
       [1, 5, 4, 1, 3, 7, 2, 2, 5, 4],
       [8, 6, 3, 4, 3, 8, 3, 2, 3, 6],
       [2, 4, 2, 4, 3, 2, 3, 3, 4, 8],
       [2, 2, 6, 5, 6, 3, 5, 8, 4, 2]])

In [9]:
def find_adjacent_coords(row,col,shape):
  row_start = max(0,row-1)
  row_end = min(shape[1]-1,row+1)
  col_start = max(0,col-1)
  col_end = min(shape[0]-1,col+1)
  row_range = np.arange(row_start,row_end+1,1)
  col_range = np.arange(col_start,col_end+1,1)

  neighbor_coords = []
  for rowi in row_range:
    for coli in col_range:
      neighbor_coords += [(rowi,coli)]
  neighbor_coords = [c for c in neighbor_coords if c != (row,col)]
  return neighbor_coords

def count_neighbors_above_threshold(x,y,grid):
  neighbors = find_adjacent_coords(x,y,grid.shape)
  neighbor_values = [grid[n] for n in neighbors]
  cnt_neighbors = (np.array(neighbor_values) >= 10).sum()
  # print([(x,y), cnt_neighbors, neighbors])
  return cnt_neighbors



grid = input.copy()
threshold = 10
sum_flashes = 0

cnt_flashing_list = []
update_grid = np.zeros(grid.shape)
update_grid = update_grid + 1
update_sum = 0

for i in range(600):
  grid += 1
  flashed_list = []
  for _ in range(15):
    for row in range(grid.shape[0]):
      for col in range(grid.shape[1]):
        if grid[row,col] >= 10 and (row,col) not in flashed_list:
          flashed_list += [(row,col)]
          for coords in find_adjacent_coords(row,col,grid.shape):
            grid[coords] += 1
        # update_grid_temp[row,col] = count_neighbors_above_threshold(row,col,(grid+update_grid))
  update_sum += (grid>=threshold).sum()
  if i == 99:
    print(f"Sum after 99 steps {update_sum}")
  if (grid>=threshold).sum() == (grid.shape[0] * grid.shape[1]):
    print(f"Synchronized on step {i+1}")
  grid = np.where(grid>=threshold,0,grid)
  # print(f"After step {i+1}")
  # print(grid)
print(update_sum)
print(grid)

Sum after 99 steps 1613
Synchronized on step 510
Synchronized on step 520
Synchronized on step 530
Synchronized on step 540
Synchronized on step 550
Synchronized on step 560
Synchronized on step 570
Synchronized on step 580
Synchronized on step 590
Synchronized on step 600
8864
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [10]:
(grid>=threshold).sum()

0