In [8]:
import numpy as np

In [9]:
aoc_day = '2021-12-13'
test_input_file = f"../test_inputs/{aoc_day}-input.txt"
test_folds_file = f"../test_inputs/{aoc_day}-input_folds.txt"
input_file = f"../inputs/{aoc_day}-input.txt"
folds_file = f"../inputs/{aoc_day}-input_folds.txt"
try_test_input = False


def preprocess_input(input:str) -> list:
    input = [tuple([int(xx) for xx in x.split(",")]) for x in input.split("\n") if x != '']
    return input 

def preprocess_input_folds(folds:str) -> list:
    folds = [x.replace('fold along ','') for x in folds.split("\n") if x != '']
    folds = [x.split('=') for x in folds]
    for x in folds:
      x[1] = int(x[1])
    return folds 

with open(test_input_file, 'r') as f:
    test_input = preprocess_input(f.read())

with open(input_file, 'r') as f:
    input = preprocess_input(f.read())
    
with open(test_folds_file, 'r') as f:
    test_folds = preprocess_input_folds(f.read())

with open(folds_file, 'r') as f:
    folds = preprocess_input_folds(f.read())

if try_test_input:
    input = test_input.copy()
    folds = test_folds.copy()

input[0:10], folds[0:10]

([(92, 632),
  (795, 9),
  (1034, 368),
  (1230, 233),
  (969, 816),
  (1218, 526),
  (971, 780),
  (139, 417),
  (892, 313),
  (1196, 196)],
 [['x', 655],
  ['y', 447],
  ['x', 327],
  ['y', 223],
  ['x', 163],
  ['y', 111],
  ['x', 81],
  ['y', 55],
  ['x', 40],
  ['y', 27]])

In [10]:
def make_grid(input):
  max_x = max([x[0] for x in input])
  max_y = max([x[1] for x in input])
  grid_shape = (max_y+1, max_x+1)
  grid = np.zeros(grid_shape)
  for x,y in input:
    grid[y,x] += 1
  return grid

def fold_paper(grid, fold_axis,fold_index): 
  if fold_axis == 'y':
    grid_0 = grid[:fold_index,:]
    grid_1 = grid[fold_index+1:,:][::-1,:]
  elif fold_axis == 'x':
    grid_0 = grid[:,:fold_index]
    grid_1 = grid[:,fold_index+1:][:,::-1]
  return grid_0, grid_1

def add_grids(grid_0, grid_1):
  if grid_0.shape == grid_1.shape:
    return grid_0 + grid_1
  #mismatched horizontal
  elif grid_0.shape[0] != grid_1.shape[0]:
    additional_rows = abs(grid_0.shape[0] - grid_1.shape[0])
    additional_row_grid = np.zeros((additional_rows,grid_0.shape[1]))
    if grid_0.shape[0] < grid_1.shape[0]:
      grid_0 = np.vstack([additional_row_grid,grid_0])
    else:
      grid_1 = np.vstack([additional_row_grid,grid_1])
  #mismatched veritcal 
  elif grid_0.shape[1] != grid_1.shape[1]:
    additional_cols = abs(grid_0.shape[1] - grid_1.shape[1])
    additional_col_grid = np.zeros((grid_0.shape[0],additional_cols))
    if grid_0.shape[1] < grid_1.shape[1]:
      grid_0 = np.hstack([grid_0,additional_col_grid])
    else:
      grid_1 = np.hstack([grid_1,additional_col_grid])
  return grid_0 + grid_1

# try:
#   new_grid = grid_0 + grid_1
#   return [grid_0, grid_1, new_grid]
# except:
#   print("mismatched dimensions")
#   return [grid_0, grid_1]



def count_dots(grid):
  return (grid >= 1).sum()




In [11]:
grid = make_grid(input)
n_folds = 0
for f in folds:
  grid_0, grid_1 = fold_paper(grid, f[0],f[1])
  n_folds += 1
  # grid = grid_0 + grid_1
  grid = add_grids(grid_0,grid_1)
  print(f"Dot Count after {n_folds} folds: {count_dots(grid)}")
  print(grid)


Dot Count after 1 folds: 790
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Dot Count after 2 folds: 660
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Dot Count after 3 folds: 539
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Dot Count after 4 folds: 453
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Dot Count after 5 folds: 382
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Dot Count after 6 folds: 314
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 

## Part Two

Finish folding the transparent paper according to the instructions. The manual says the code is always eight capital letters.



Since the shape of the final grid is (6,40). Since 40 is divisible by 8, let's try printing 8 equally sized (6,5) subsets of the grid. 

In [12]:
start = 0
increment_lenth = int(grid.shape[1] / 8)
for i in range(8):
  print(i)
  print(np.where(grid>= 1,'#','.')[:,start:start+increment_lenth])
  start += increment_lenth

0
[['#' '#' '#' '.' '.']
 ['#' '.' '.' '#' '.']
 ['#' '.' '.' '#' '.']
 ['#' '#' '#' '.' '.']
 ['#' '.' '.' '.' '.']
 ['#' '.' '.' '.' '.']]
1
[['.' '#' '#' '.' '.']
 ['#' '.' '.' '#' '.']
 ['#' '.' '.' '.' '.']
 ['#' '.' '#' '#' '.']
 ['#' '.' '.' '#' '.']
 ['.' '#' '#' '#' '.']]
2
[['#' '.' '.' '#' '.']
 ['#' '.' '.' '#' '.']
 ['#' '#' '#' '#' '.']
 ['#' '.' '.' '#' '.']
 ['#' '.' '.' '#' '.']
 ['#' '.' '.' '#' '.']]
3
[['#' '#' '#' '#' '.']
 ['.' '.' '.' '#' '.']
 ['.' '.' '#' '.' '.']
 ['.' '#' '.' '.' '.']
 ['#' '.' '.' '.' '.']
 ['#' '#' '#' '#' '.']]
4
[['#' '#' '#' '.' '.']
 ['#' '.' '.' '#' '.']
 ['#' '#' '#' '.' '.']
 ['#' '.' '.' '#' '.']
 ['#' '.' '.' '#' '.']
 ['#' '#' '#' '.' '.']]
5
[['#' '#' '#' '#' '.']
 ['#' '.' '.' '.' '.']
 ['#' '#' '#' '.' '.']
 ['#' '.' '.' '.' '.']
 ['#' '.' '.' '.' '.']
 ['#' '.' '.' '.' '.']]
6
[['.' '.' '#' '#' '.']
 ['.' '.' '.' '#' '.']
 ['.' '.' '.' '#' '.']
 ['.' '.' '.' '#' '.']
 ['#' '.' '.' '#' '.']
 ['.' '#' '#' '.' '.']]
7
[['.' '#' '