In [1]:
import numpy as np

https://adventofcode.com/2021/day/6

In [ ]:
def count_fish_population(fish):
  fish_pop = []
  for i in range(9):
    fish_pop += [(fish == i).sum()]
  return fish_pop

In [7]:
# starting_fish = np.array([3,4,3,1,2])
starting_fish = np.array([5,1,4,1,5,1,1,5,4,4,4,4,5,1,2,2,1,3,4,1,1,5,1,5,2,2,2,2,1,4,2,4,3,3,3,3,1,1,1,4,3,4,3,1,2,1,5,1,1,4,3,3,1,5,3,4,1,1,3,5,2,4,1,5,3,3,5,4,2,2,3,2,1,1,4,1,2,4,4,2,1,4,3,3,4,4,5,3,4,5,1,1,3,2,5,1,5,1,1,5,2,1,1,4,3,2,5,2,1,1,4,1,5,5,3,4,1,5,4,5,3,1,1,1,4,5,3,1,1,1,5,3,3,5,1,4,1,1,3,2,4,1,3,1,4,5,5,1,4,4,4,2,2,5,5,5,5,5,1,2,3,1,1,2,2,2,2,4,4,1,5,4,5,2,1,2,5,4,4,3,2,1,5,1,4,5,1,4,3,4,1,3,1,5,5,3,1,1,5,1,1,1,2,1,2,2,1,4,3,2,4,4,4,3,1,1,1,5,5,5,3,2,5,2,1,1,5,4,1,2,1,1,1,1,1,2,1,1,4,2,1,3,4,2,3,1,2,2,3,3,4,3,5,4,1,3,1,1,1,2,5,2,4,5,2,3,3,2,1,2,1,1,2,5,3,1,5,2,2,5,1,3,3,2,5,1,3,1,1,3,1,1,2,2,2,3,1,1,4,2])

transition_matrix = np.zeros((9,9))

for i in range(9):
  try:
    transition_matrix[i+1,i] = 1
  except:
    pass
transition_matrix[0,8] = 1 
transition_matrix[0,6] = 1 

print("Transition matrix")
print(transition_matrix)

fish = np.array(count_fish_population(starting_fish))

print("Starting fish")
print(fish)
days = 256

for i in range(1,days + 1):
  fish = np.matmul(fish,transition_matrix)
  if (i % 10 == 0) or (i == days):
    print(f"After {i} days: {fish.sum()}")



Transition matrix
[[0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Starting fish
[ 0 96 54 48 51 51  0  0  0]
After 10 days: 750.0
After 20 days: 1992.0
After 30 days: 4593.0
After 40 days: 10497.0
After 50 days: 26139.0
After 60 days: 62031.0
After 70 days: 147417.0
After 80 days: 355386.0
After 90 days: 837552.0
After 100 days: 2025447.0
After 110 days: 4839195.0
After 120 days: 11443596.0
After 130 days: 27672981.0
After 140 days: 65771748.0
After 150 days: 156774966.0
After 160 days: 377399241.0
After 170 days: 895529862.0
After 180 days: 2146039836.0
After 190 days: 5140774788.0
After 200 days: 12220225728.0
After 210 days: 29334033681.0
After 220 days: 70018746918.0
After 230 days: 166951018581.0
After 240 days: 400431510900.0
After 250 days: 954356387721.0
Afte